#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Holger Kinkelin
2015/01/02

Replaces most common "special" characters found in (European) 
languages with their html code counterparts
"""

def htmlEscape(input):
	result = input
	# important to replace "&"" at first as it will spoil later replacements
	result = result.replace("&", "&amp;") 
	result = result.replace("À", "&Agrave;")
	result = result.replace("à", "&agrave;")
	result = result.replace("Á", "&Aacute;")
	result = result.replace("á", "&aacute;")
	result = result.replace("Â", "&Acirc;")
	result = result.replace("â", "&acirc;")
	result = result.replace("Ã", "&Atilde;")
	result = result.replace("ã", "&atilde;")
	result = result.replace("ã", "&atilde;")
	result = result.replace("Ä", "&Auml;")
	result = result.replace("ä", "&auml;")
	result = result.replace("Å", "&Aring;")
	result = result.replace("å", "&aring;")
	result = result.replace("Æ", "&AElig;")
	result = result.replace("æ", "&aelig;")
	result = result.replace("ª", "&ordf;")
	result = result.replace("Ç", "&Ccedil;")
	result = result.replace("ç", "&ccedil;")
	result = result.replace("È", "&Egrave;")
	result = result.replace("è", "&egrave;")
	result = result.replace("É", "&Eacute;")
	result = result.replace("é", "&eacute;")
	result = result.replace("Ê", "&Ecirc;")
	result = result.replace("ê", "&ecirc;")
	result = result.replace("Ë", "&Euml;")
	result = result.replace("ë", "&euml;")
	result = result.replace("Ì", "&Igrave;")
	result = result.replace("ì", "&igrave;")
	result = result.replace("Í", "&Iacute;")
	result = result.replace("í", "&iacute;")
	result = result.replace("Î", "&Icirc;")
	result = result.replace("î", "&icirc;")
	result = result.replace("Ï", "&Iuml;")
	result = result.replace("ï", "&iuml;")
	result = result.replace("Ñ", "&Ntilde;")
	result = result.replace("ñ", "&ntilde;")
	result = result.replace("Ò", "&Ograve;")
	result = result.replace("ò", "&ograve;")
	result = result.replace("Ó", "&Oacute;")
	result = result.replace("ó", "&oacute;")
	result = result.replace("Ô", "&Ocirc;")
	result = result.replace("ô", "&ocirc;")
	result = result.replace("Õ", "&Otilde;")
	result = result.replace("õ", "&otilde;")
	result = result.replace("Ö", "&Ouml;")
	result = result.replace("ö", "&ouml;")
	result = result.replace("Ø", "&Oslash;")
	result = result.replace("ø", "&oslash;")
	result = result.replace("ß", "&szlig;")
	result = result.replace("Ù", "&Ugrave;")
	result = result.replace("ù", "&ugrave;")
	result = result.replace("Ú", "&Uacute;")
	result = result.replace("ú", "&uacute;")
	result = result.replace("Û", "&Ucirc;")
	result = result.replace("û", "&ucirc;")
	result = result.replace("Ü", "&Uuml;")
	result = result.replace("ü", "&uuml;")
	result = result.replace("Ü", "&Uuml;")
	result = result.replace("ü", "&uuml;")
	result = result.replace("ÿ", "&yuml;")
	result = result.replace("Ý", "&Yacute;")
	result = result.replace("ý", "&yacute;")
	result = result.replace("°", "&deg;")
	result = result.replace("¡", "&iexcl;")
	result = result.replace("¿", "&iquest;")
	result = result.replace("¦", "&brvbar;")
	result = result.replace("©", "&copy;")
	result = result.replace("®", "&reg;")
	result = result.replace("", "&euro;")
	result = result.replace("¢", "&cent;")
	result = result.replace("£", "&pound;")
	result = result.replace("¤", "&curren;")
	result = result.replace("¥", "&yen;")
	result = result.replace("\"", "&quot;")
	result = result.replace("´", "&acute;")
	result = result.replace("«", "&laquo;")
	result = result.replace("»", "&raquo;")
	result = result.replace("<", "&lt;")
	result = result.replace(">", "&gt;")
	result = result.replace("×", "&times;")
	result = result.replace("÷", "&divide;")
	result = result.replace("±", "&plusmn;")
	result = result.replace("", "&hellip;")
	result = result.replace("Œ", "&OElig;")
	result = result.replace("œ", "&oelig;")
	result = result.replace("§", "&sect;")
	result = result.replace("¨", "&uml;")
	result = result.replace("¬", "&not;")
	result = result.replace("­", "&shy;")
	result = result.replace("µ", "&micro;")
	result = result.replace("¶", "&para;")
	result = result.replace("·", "&middot;")
	result = result.replace("¸", "&cedil;")
	result = result.replace("º", "&ordm;")
	result = result.replace("Ð", "&ETH;")
	result = result.replace("Þ", "&THORN;")
	result = result.replace("ð", "&eth;")
	result = result.replace("þ", "&thorn;")
	result = result.replace("²", "&sup2;")
	result = result.replace("³", "&sup3;")
	return result